config/routes.rb
Rails.application.routes.draw do
  get 'menus/index'
  devise_for :users
  devise_for :admins, controller: {
    sessions: 'admins/sessions'
   }
  root 'recipes#index'
  resources :recipes 
  resources :menus, only: [:index, :new, :create]
  get '/carender/:date', to: 'menus#new', as: :new_menu_for_date
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :room_users
  has_many :recipes, through: :recipe_menu
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
    @recipes = Recipe.all
  end

  def new
    @selected_date = params[:date].present? ? Date.parse(params[:date]) : Date.today
    @day_of_week = @selected_date.strftime('%A')
    @menu = Menu.new
    search_term = params[:recipe_search_term]
    @recipes = Recipe.where("name LIKE ?", "%#{search_term}%") if search_term.present?
  end
  
  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to root_path
    else
      renndr :new
    end  
  end  


  private

  def menu_params
    params.require(:menu).permit(:date, :name, :description)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/index.html.erb
<%= render "shared/header" %>

<div class='manu-main'>  
  <div class='calender-text'>
    献立カレンダー
  </div>
  <div class='manu-text'>
    献立を作成したい日付をクリックしてください
  </div>  
  
  <div class='calender'> 
   <%= month_calendar events: @menus do |date,all| %>
     <%= link_to new_menu_for_date_path(date), class: 'crender-date-menu' do %>
   <%= date.day %>
   <%= all.each do |menu| %>
  <%end%> 
<% end %>
<% end %>
</div>
</div>



<%= render  "shared/footer" %>

app/views/menus/new.html.erb
<div class='menu-new-mian'>
 <div class='menu-new-text'>
   献立をたてる
 </div>

 <div class='menu-new-calender'>
   <div class='menu-new-date'>
     <%= "#{@selected_date.strftime('%m月%d日')}分の献立を作成"%> 
   </div>
   <div class='new-menus'>
     <%= form_tag(new_menu_for_date_path(@selected_date), method: :get, class: 'menu-form') do %>
     <%= select_tag(:category_id, options_for_select(Category.all.map { |c| [c.name, c.id] }), prompt: 'カテゴリーを選択') %>
     <%= text_field_tag(:search_term, params[:search_term], placeholder: 'レシピ名または材料で検索') %>
     <%= submit_tag '検索' %>
    <% if @recipes.present? %>
    <% @recipes.each do |recipe| %>
       <p><%= recipe.title %></p>
       <%end%>
       <% else %>
       検索結果はありません
    <% end %>
   <%end%> 
 <%= link_to "カレンダーに戻る", menus_path %>
  </div>    