config/routes.rb
Rails.application.routes.draw do
  get 'menus/index'
  devise_for :users
  devise_for :admins, controller: {
    sessions: 'admins/sessions'
   }
  root 'recipes#index'
  resources :recipes 
  resources :menus, only: [:index, :new, :create]
  get '/carender/:date', to: 'menus#new', as: :new_menu_for_date
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :admin
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipe_seasonings, dependent: :destroy
  has_many :recipe_steps, dependent: :destroy
  has_many :room_users
  has_many :menus, through: :recipe_menu

  accepts_nested_attributes_for :recipe_ingredients,
                                :recipe_seasonings,
                                :recipe_steps, reject_if: :all_blank, allow_destroy: true
  
  validates :image, :title, presence: true
  validates :category_id, numericality: { other_than: 0 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  #before_action :admin_scan, only: [:edit]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @recipe_ingredients = @recipe.recipe_ingredients.build
    @recipe_seasonings = @recipe.recipe_seasonings.build
    @recipe_steps = @recipe.recipe_steps.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if current_user&.admin?
      @recipe.admin_id = current_user.id
    end
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end     

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
  end  

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path
    else
      render :edit
    end
  end   
  
  def destroy
    @recipe.destroy
    redirect_to root_path
  end  

  private
  #def admin_scan
    #unless current_user&.admin?
      #redirect_to root_path
   #end  
  #end

  def recipe_params
    params.require(:recipe).permit(
      :image, :title, :category_id, 
      recipe_ingredients_attributes: [:id, :name, :quantity, :_destroy], 
      recipe_seasonings_attributes: [:id, :name, :quantity, :_destroy], 
      recipe_steps_attributes: [:id, :name, :_destroy])
      .merge(admin_id: current_admin.id)  
  end  

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end  
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe_ingredient_fields.html.erb
<div class="nested-fields">
  <div class='ingredient-fields'>
    <div class='new-group'> 
    <%= f.text_field :name, class: "ingredients-input" %>
      <div class='quantity-text'>分量</div>
      <%= f.text_field :quantity, class: "quantity-input" %>
      <%= link_to_remove_association "削除する", f, class:'new-add-btn'%>
    </div>
  </div>
</div>   

 

app/views/recipes/_recipe_seasoning_fields.html.erb
<div class="nested-fields">
  <div class='seasoning-fields'>
    <div class='new-group'> 
      <%= f.text_field :name, class: "seasonings-input" %>
      <div class='quantity-text'>分量</div>
      <%= f.text_field :quantity, class: "quantity-input" %>
      <%= link_to_remove_association "削除する", f, class:'new-add-btn'%>
    </div>
  </div>      
</div>

app/views/recipes/_recipe_step_fields.html.erb
<div class="nested-fields">
  <div class="step-fields">
    <%= f.text_field :name, class:'step-amount', id:'step-amount' %>
    <%= link_to_remove_association '削除する', f, class:'new-add-btn' %>
  </div>
</div>  

app/views/recipes/edit.html.erb
<div class='recipe-new'>
  <div class='recipe-contents'>
    <div class='recipe-new-title'>
      レシピを編集
    </div>   
    <%= form_with model: @recipe, url: recipe_path(@recipe), local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class='new-items'>
    <%# 料理画像 %>
      <div class='new-item'>
        <div class="recipe-new-text">料理画像 </div>
          <%= f.file_field :image, id: "item-image" %>
      </div>  

    <%# 料理名 %>
      <div class='new-item'>
        <div class="recipe-new-text">料理名</div>
          <%= f.text_field :title, class:'title-input'%>
      </div>

    <%# 料理カテゴリー %>
      <div class='new-item'>
        <div class="recipe-new-text">分類</div>
          <%= f.collection_select :category_id, Category.all, :id, :name %>
      </div>
      
    <%# 食材 %>
      <div class="new-item">
        <div class='recipe-text-box'>
          <div class="recipe-new-text">食材</div>
          <div class='new-ingredient-btn'>
          <%= link_to_add_association "追加する", f, :recipe_ingredients,
          class: 'ingredient-btn',
          data:{
          association_insertion_node: '#new-ingredient-field',
          association_insertion_method: 'after'
          }
          %>  
         </div>
       </div>
       <%= f.fields_for :recipe_ingredients do |form| %>
         <%= render "recipes/recipe_ingredient_fields", f: f %>
       <% end %>
         <div id="new-ingredient-field"></div>
      </div>

    <%# 調味料 %>
      <div class="new-item">
        <div class='recipe-text-box'>
          <div class='recipe-new-text'>調味量 </div>
          <div class='new-seasoning-btn'>
          <%= link_to_add_association "追加する", f, :recipe_seasonings ,
          class: 'seasoning-btn',
          data:{
          association_insertion_node: '#new-seasoning-field',
          association_insertion_method: 'after'
          }
          %>  
          </div>
        </div>
        <%= f.fields_for :recipe_seasonings do |form| %>
          <%= render "recipes/recipe_seasoning_fields", f: f %>
        <% end %>
        <div id="new-seasoning-field"></div>
      </div>   
     
    <%# 作り方 %>
      <div class="new-item">
        <div class='recipe-text-box'>
          <div class="recipe-new-text" >作り方</div>
          <div class='new-step-btn'>
          <%= link_to_add_association "追加する", f, :recipe_steps,
          class: 'steps-btn',
          data:{
          association_insertion_node: '#nwe-step-fild',
          association_insertion_method: 'after'
          }
          %>  
         </div>
       </div> 
       <%= f.fields_for :recipe_steps do |form| %>
         <%= render "recipes/recipe_step_fields", f: f %>
        <% end %>
        <div id="nwe-step-fild"></div>
      </div>
    
    <%# 編集ボタン %>
      <div class="new-btn-contents">
        <%= f.submit "変更する" , class:"new-btn" %>
        <%= link_to '削除する', recipe_path, method: :delete, class: 'destroy-btn'%>
        <%= link_to "戻る", recipes_path, class:'back-btn' %> 
      </div>
    <% end %>
  </div>
</div>


 

app/views/recipes/index.html.erb
<%= render "shared/header" %>

<%# レシピ一覧 %>
 <div class='recipe-contents'>
   <ul class='recipe-lists'>
     <% @recipes.each do |recipe| %>
       <li class='-recipe-list'>
         <%= link_to recipe_path(recipe.id) do %>
           <div class='recipe-img-content'>
             <%= image_tag recipe.image, class: "recipe-img"%>
           </div>
           <div class='recipe-info'>
             <div class='recipe-title'>
               <%= recipe.title %>
             </div>
           </div> 
          <% end %>    
        </li>    
     <% end %>
   </ul>
 </div> 
<%= render "shared/footer" %>    

app/views/recipes/new.html.erb
<div class='recipe-new'>
  <div class='recipe-new-title'>
    レシピ作成
  </div>   
  <%= form_with model: @recipe, url: recipes_path, local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class='new-items'>
    <%# 料理画像 %>
      <div class='new-item'>
        <div class="recipe-new-text">料理画像 </div>
        <%= f.file_field :image, id: "item-image" %>
      </div>  

    <%# 料理名 %>
      <div class='new-item'>
        <div class="recipe-new-text">料理名</div>
        <%= f.text_field :title, class:'title-input'%>
      </div>

    <%# 料理カテゴリー %>
      <div class='new-item'>
        <div class="recipe-new-text">分類</div>
        <%= f.collection_select :category_id, Category.all, :id, :name, class: 'category-input' %>
      </div>
      
    <%# 食材 %>
      <div class="new-item">
        <div class='recipe-text-box'>
          <div class="recipe-new-text">食材</div>
          <div class='new-ingredient-btn'>
          <%= link_to_add_association "追加する", f, :recipe_ingredients,
          class: 'ingredient-btn',
          data:{
          association_insertion_node: '#new-ingredient-field',
          association_insertion_method: 'append'
          }%>  
         </div>
       </div>
       <%= f.fields_for :recipe_ingredients do |form| %>
         <%= render "recipes/recipe_ingredient_fields", f: form %>
       <% end %>
       <div  id='new-ingredient-field'></div>
      </div>

    <%# 調味料 %>
      <div class="new-item">
        <div class='recipe-text-box'>
          <div class='recipe-new-text'>調味量 </div>
          <div class='new-seasoning-btn'>
          <%= link_to_add_association "追加する", f, :recipe_seasonings ,
          class: 'seasoning-btn',
          data:{
          association_insertion_node: '#new-seasoning-field',
          association_insertion_method: 'append'
          }
          %>  
          </div>
        </div>
        <%= f.fields_for :recipe_seasonings do |form| %>
          <%= render "recipes/recipe_seasoning_fields", f: form %>
        <% end %>
        <div id="new-seasoning-field"></div>
      </div>   
     
    <%# 作り方 %>
      <div class="new-item">
        <div class="recipe-new-text" >作り方</div>
        <div class='steps'> 
          <%= f.fields_for :recipe_steps do |form| %>
            <%= render "recipes/recipe_step_fields", f: form %>
          <% end %>
        </div>  
        <div id='nwe-step-fild'></div>
        <div class='new-step-btn'>
          <%= link_to_add_association "追加する", f, :recipe_steps,
          class: 'steps-btn',
          data:{
          association_insertion_node: '#nwe-step-fild',
          association_insertion_method: 'append'
          }%>  
         </div>
        </div> 
    
    <%# 作成ボタン %>
      <div class="new-btn-contents">
      <%= f.submit "作成する" , class:"new-btn" %>
      <%= link_to "戻る", recipes_path, class:'back-btn' %> 
      </div>
    <% end %>
  </div>
</div>


 

app/views/recipes/show.html.erb
<%= render "shared/header" %>

<%# レシピ詳細表示 %>
 <div class='recipe-show'>
   <div class='recipe-contents'>
     <div class='recipe-box'> 

      <%# レシピ画像 %>
      <div class='recipe-img-content'>
        <%= image_tag @recipe.image, class:'recipe-box-img' %>
      </div>
      <div class='datail-table'>

       <%# 料理名 %>
       <div class='datail-title'>
         <%= @recipe.title %>
       </div> 

       <%# 材料詳細 %>
       <div class='show-item'>
        <div class='datail-ingredients'>
          材料
        </div>
        <% if @recipe.recipe_ingredients.present? %>
          <% @recipe.recipe_ingredients.each do |ingredient| %>
          <div class='datail-item'>
            <%= ingredient.name %>  
            <div class='datail-quantity'>
              <%= ingredient.quantity %>
            </div>
          </div>
         <% end %> 
        <%end %> 
       <%# 調味料詳細 %> 
       <div class='datail-seasonings'>
         【調味料】
       </div> 
       <% if @recipe.recipe_seasonings.present? %>
         <% @recipe.recipe_seasonings.each do |seasoning| %>
         <div class='datail-item'>  
           （A）<%= seasoning.name %>
           <div class='datail-quantity'>
             <%= seasoning.quantity %>
           </div> 
         </div> 
         <% end %> 
       <% end %>

       <%# 作り方詳細 %>
       <div class='datail-steps'> 
         作り方
       </div>
       <% if @recipe.recipe_steps.present? %>
         <% @recipe.recipe_steps.each do |step| %>
         <div class='datail-item'>
           <%= step.name%> 
         </div> 
         <% end %> 
       <% end %> 
    </div>
  </div> 
  <div class='recipe-carender-form'>
    <%= form_for @recipe, url: { action: :create_menu }, remote: true, method: :post, class: 'recipe-date-form' do |form| %>
    <%= form.date_field :sample_at, value: @recipe.sample_at, class: 'recipe-date-field' %>
    <%= form.submit '献立を登録する', class: 'recipe-date-btn' %>
  <% end %>
  </div>
 </div>  
<%= link_to '戻る', recipes_path, class: 'show-back-btn' %>

  <%if admin_signed_in? %>
  <div class='show-btn-contents'>
    <%= link_to '編集する', edit_recipe_path, method: :get, class: 'show-btn' %>
  </div>
  <% end %>
  


 